
# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# -----------------------------------------------------------------------------------------------------------------------
# Alias
# -----------------------------------------------------------------------------------------------------------------------

alias ls='ls -hF --color=tty'
alias ll='ls -laF'
alias la='ls -A'
alias l='ls -CF'
alias e='exit'
alias c='clear'

# -----------------------------------------------------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------------------------------------------------

git-prune-branches-dry-run() {
    git fetch --dry-run --prune origin
    git fetch origin && git branch --merged origin/master | grep -vE ' master$|^\*' | xargs echo git branch -d
}

git-prune-branches () {
    git fetch --prune origin && git branch --merged origin/master | grep -vE ' master$|^\*' | xargs git branch -d
}

