
# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Functions
if [ -f $HOME/.dotfiles/conf/functions ]; then
    source $HOME/.dotfiles/conf/functions
fi

# -----------------------------------------------------------------------------------------------------------------------
# Alias
# -----------------------------------------------------------------------------------------------------------------------

alias ls='ls -hF --color=tty'
alias ll='ls -laF'
alias la='ls -A'
alias l='ls -CF'
alias e='exit'
alias c='clear'

