# 補完機能
autoload -Uz compinit
compinit

# 予測機能
#autoload -Uz predict-on
#predict-on

# 色機能
autoload -Uz colors
colors

# プロンプトの設定
autoload -Uz vcs_info
autoload -Uz add-zsh-hook
zstyle ':vcs_info:*' enable git svn hg
zstyle ':vcs_info:*' stagedstr "+"
zstyle ':vcs_info:*' unstagedstr "-"
zstyle ':vcs_info:*' formats '%s %b %c%u'
zstyle ':vcs_info:*' actionformats '%s %b [%a] %c%u'
zstyle ':vcs_info:*' branchformat '%b:%r'
zstyle ':vcs_info:*' use-simple true
zstyle ':vcs_info:*' check-for-changes true
function updateMessage() {
    psvar=()
    LANG=en_US.UTF-8 vcs_info
    if [[ -n "$vcs_info_msg_0_" ]]; then
        psvar[1]="$vcs_info_msg_0_"
    fi
}
add-zsh-hook precmd updateMessage
PS1="%{$fg[cyan]%}
> %~%1v
rskull@mac${WINDOW:+"[$WINDOW]"}\$ %{${reset_color}%}"
#%m${WINDOW:+"[$WINDOW]"}%# %{${reset_color}%}"

# エイリアスの設定
alias ls='ls -GF'
alias ll='ls -la'
alias man='jman'
alias screen='screen -U'
alias c='clear'
alias h='history'
alias e='exit'
alias pressjs='uglifyjs'
alias javac='javac -J-Dfile.encoding=UTF-8'
alias java='java -Dfile.encoding=UTF-8'
alias cds='cd /Applications/MAMP/htdocs'
alias rmdss='find . -name .DS_Store -print0 | xargs -0 rm'
alias apache='php -S 192.168.11.2:8000'
alias mysql='/Applications/MAMP/Library/bin/mysql'
alias dev-db='/Applications/MAMP/Library/bin/mysql -uroot -proot -hlocalhost'


alias cot='open -g -a CotEditor' # ターミナルからCotEditorを開く
alias safari='open -g -a safari' # ターミナルからSafariを開く
alias console='open -a console' # ターミナルからコンソールを開く

# php applications
alias psh='cd /Users/rskull/psh/;sh psh.sh'
alias twist='cd /Users/rskull/twister; sh twister.sh'
alias imget='php /Users/rskull/program/php/getImg/getImg.php'

# node.js
# source ~/.nvm/nvm.sh
# nvm use v0.6.8 > /dev/null

export WORDCHARS='*?_.[]~=&;!#$%^(){}<>' #区切り文字
setopt list_packed #リストを詰めて表示
setopt nolistbeep #ビープ音を鳴らさない
setopt auto_pushd #cdのときにpushdする
setopt correct #間違えたコマンドの時、候補表示

# 補完候補の色づけ
export ZLS_COLORS=$LS_COLORS
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' #大小文字を区別せずに補完
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin #sudoでも補完する
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([%0-9]#)*=0=01;31' #プロセス番号とジョブの色付け
zstyle ':completion:*:default' menu yes select=1 #補完候補のカーソル選択

setopt glob #ファイルグロブ
setopt extendedglob #拡張グロブ
#setopt glob_dots #ドットファイルも普通のファイルと同様に扱う

# スクリーンで開始する
#if [ $SHLVL = 1 ]; then
#    screen -R
#fi


PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

export PATH=/opt/local/bin:/opt/local/sbin:$PATH
