# Functions
if [ -f $HOME/.dotfiles/conf/functions ]; then
    source $HOME/.dotfiles/conf/functions
fi

# 補完機能
autoload -Uz compinit
compinit

# 予測機能
# autoload -Uz predict-on
# predict-on

# 色機能
autoload -Uz colors
colors

# プロンプトの設定
autoload -Uz vcs_info
autoload -Uz add-zsh-hook
zstyle ':vcs_info:*' enable git svn hg
zstyle ':vcs_info:*' stagedstr "+"
zstyle ':vcs_info:*' unstagedstr "-"
zstyle ':vcs_info:*' formats '%s %b %c%u'
zstyle ':vcs_info:*' actionformats '%s %b [%a] %c%u'
zstyle ':vcs_info:*' branchformat '%b:%r'
zstyle ':vcs_info:*' use-simple true
zstyle ':vcs_info:*' check-for-changes true

function updateMessage() {
    psvar=()
    LANG=en_US.UTF-8 vcs_info
    if [[ -n "$vcs_info_msg_0_" ]]; then
        psvar[1]="$vcs_info_msg_0_"
    fi
}

add-zsh-hook precmd updateMessage

PROMPT="%{${fg[cyan]}%}[%n@%m]%{${reset_color}%} %~
\$ "

export LSCOLORS=cxfxcxdxbxegedabagacad

# エイリアスの設定
alias ls='ls -F --color=auto'
alias ll='ls -la -F --color=auto'
alias screen='screen -U'
alias c='clear'
alias h='history'
alias e='exit'
alias pressjs='uglifyjs'
alias rmdss='find . -name .DS_Store -print0 | xargs -0 rm'

alias cot='open -g -a CotEditor'    # ターミナルからCotEditorを開く
alias safari='open -g -a safari'    # ターミナルからSafariを開く
alias console='open -a console'     # ターミナルからコンソールを開く

export WORDCHARS='*?_.[]~=&;!#$%^(){}<>' # 区切り文字

setopt list_packed  # リストを詰めて表示
setopt nolistbeep   # ビープ音を鳴らさない
setopt auto_pushd   # cdのときにpushdする
setopt correct      # 間違えたコマンドの時、候補表示

# 補完候補の色づけ
export ZLS_COLORS=$LS_COLORS
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # 大小文字を区別せずに補完
zstyle ':completion:*:default' menu yes select=1    # 補完候補のカーソル選択
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin # sudoでも補完する
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([%0-9]#)*=0=01;31' # プロセス番号とジョブの色付け

setopt glob             # ファイルグロブ
setopt extendedglob     # 拡張グロブ

export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# scala
export PATH=$PATH:/usr/local/src/scala/bin
export SCALA_HOME=/usr/local/src/scala

# activator
export PATH=$PATH:/usr/local/src/activator

# packer
export PATH=/usr/local/packer:$PATH
